services:
  identity-service:
    image: felipersd/portal-financeiro-identity-service:production
    container_name: portal-financeiro-identity
    restart: always
    env_file:
      - ./apps/backend/identity-service/.env.production
    environment:
      - FRONTEND_URL=https://portalfinanceiro.net
    networks:
      - app-network

  finance-service:
    image: felipersd/portal-financeiro-finance-service:production
    container_name: portal-financeiro-finance
    restart: always
    env_file:
      - ./apps/backend/finance-service/.env.production
    networks:
      - app-network

  frontend:
    image: felipersd/portal-financeiro-web:production
    container_name: portal-financeiro-frontend
    restart: always
    env_file:
      - ./apps/frontend/.env.production
    networks:
      - app-network
    depends_on:
      - gateway

  gateway:
    image: felipersd/portal-financeiro-gateway:production
    container_name: portal-financeiro-gateway
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - identity-service
      - finance-service

  db:
    image: postgres:15-alpine
    container_name: portal-financeiro-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backup:
    build:
      context: ./apps/backup
      dockerfile: Dockerfile
    container_name: portal-financeiro-backup
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db
      - AWS_ACCESS_KEY_ID=22824f4caf563e876b2b3f89ed128d5f
      - AWS_SECRET_ACCESS_KEY=0d323cdbb5009c79ddd3978cc23752b42185aa6452111aeae13bd31f2a021660
      - AWS_DEFAULT_REGION=auto
      - R2_ENDPOINT_URL=https://6ce642391b1e371c914286ba7b6ca7c7.r2.cloudflarestorage.com
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: portal-financeiro-cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiNmNlNjQyMzkxYjFlMzcxYzkxNDI4NmJhN2I2Y2E3YzciLCJ0IjoiNzdlOGViMmQtZDA4NC00ZjBkLTgwODgtMTQyYzc3NmRmZDhjIiwicyI6IlpHVmxaalZsTWpFdE1qYzNZeTAwWTJJMUxXRTJNakF0TXpabU9URmhNVFUxTURWaSJ9
    restart: always
    networks:
      - app-network
    depends_on:
      - gateway

  watchtower:
    image: containrrr/watchtower
    container_name: portal-financeiro-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 30
    restart: always
    networks:
      - app-network

networks:
  app-network:


volumes:
  postgres_data:
