name: Build e Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Loga no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Gera metadados do Docker (Tags e Labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/portal-financeiro-web
          tags: |
            # Tag 'latest' apenas se for a branch default (main)
            type=raw,value=latest,enable={{is_default_branch}}
            # Tag com o short SHA do commit (ex: sha-8553c72)
            type=sha,format=short
            # Tag com a versão do git tag (ex: v1.0.0)
            type=ref,event=tag

      # 6. Constrói a imagem e envia (Push)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VITE_API_URL=http://api:3000
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}