name: Build e Push Docker Image

on:
  push:
    branches: [ "main" ] # Roda quando fizer push na main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o QEMU (Para garantir compatibilidade de arquitetura)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Configura o Docker Buildx (Motor de build moderno)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Loga no Docker Hub usando os segredos
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Constrói a imagem e envia (Push)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . # Onde está seu Dockerfile (na raiz?)
          push: true
          # Substitua 'seu-usuario/sua-imagem' pelo nome real do seu repo no Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/portal-financeiro:latest
            ${{ secrets.DOCKER_USERNAME }}/portal-financeiro:${{ github.sha }}